apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: '0'
    machine.openshift.io/memoryMb: '65536'
    machine.openshift.io/vCPU: '16'
  name: cluster-madrid-d815-cb79k-windows-eu-west-1a
  
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-madrid-d815-cb79k
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-madrid-d815-cb79k
      machine.openshift.io/cluster-api-machineset: cluster-madrid-d815-cb79k-worker-eu-west-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-madrid-d815-cb79k
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-madrid-d815-cb79k-worker-eu-west-1a
        machine.openshift.io/os-id: Windows
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ''
      providerSpec:
        value:
          userDataSecret:
            name: windows-user-data
          placement:
            availabilityZone: eu-west-1a
            region: eu-west-1
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: m5a.4xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                iops: 0
                kmsKey: {}
                volumeSize: 120
                volumeType: gp2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-madrid-d815-cb79k-worker-sg
          kind: AWSMachineProviderConfig
          tags:
            - name: kubernetes.io/cluster/cluster-madrid-d815-cb79k
              value: owned
          deviceIndex: 0
          ami:
            id: ami-0a9505a076b961d50
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-madrid-d815-cb79k-private-eu-west-1a
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: cluster-madrid-d815-cb79k-worker-profile
